name: Generate Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *'  # This will run every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the action

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Contribution Graph
        uses: Platane/snk@master
        with:
          github_user: 'RSKELT0N'  # Your GitHub username
          svg_out: 'github-contribution-grid-snake.svg'  # Output file name

      - name: Commit and push
        run: |
          git config --local user.email "your_email@example.com"  # Your email
          git config --local user.name "your_username"  # Your GitHub username
          git add github-contribution-grid-snake.svg
          git commit -m "Update contribution graph"
          git push
